systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-XX:+UseSerialGC -XX:ReservedCodeCacheSize=256m -Xmx2560m -Xms512m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.compiler.execution.strategy=in-process
org.gradle.parallel=false
org.gradle.caching=false
kotlin.daemon.enabled=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
CronetVersion=128.0.6613.40
CronetMainVersion=128
